import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from "next/dynamic"
import CatalogComponent from "../components/Catalog"
const Nav = dynamic(()=> import("main/nav"));
const Footer = dynamic(()=> import("main/footer"));

export default function Catalog() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Nav>This is the nav in app 2</Nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
            this is the catalog page
        </h1>

        <h2>They more changes</h2>
        <CatalogComponent/>
      
      </main>
    <Footer></Footer>

    </div>
  )
}
