import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from "next/dynamic"

const Nav = dynamic(()=> import("main/nav"));
const Footer = dynamic(()=> import("main/footer"));

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Nav>This is the nav in app 2</Nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Shop app port: 3001
        </h1>

      
      </main>
    <Footer></Footer>

    </div>
  )
}
